name: Deploy Python package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install Poetry
        run: |
          pipx install poetry==1.3.2
          poetry --version
          poetry self show plugins
          poetry config virtualenvs.in-project true

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Publish on PyPi
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
